# Generated by Django 3.2.20 on 2023-08-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-name']},
        ),
    ]
