# Generated by Django 3.2.20 on 2023-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
