# Generated by Django 3.2.20 on 2023-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menucategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
