# Generated by Django 3.2.20 on 2023-08-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0002_auto_20230809_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='applications',
        ),
        migrations.AddField(
            model_name='cat',
            name='applications',
            field=models.ManyToManyField(blank=True, through='cats.CatApplication', to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='catapplication',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
        migrations.AlterField(
            model_name='catapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
